version: '3.8'

services:
    postgres:
      image: postgres:13.3-alpine
      container_name: db_galaxy_auto
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=db_galaxy_auto
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres

