spring:
  profiles:
    active: ${CURRENT_ENV:dev}
    
  application:
    name: GalaxyAuto
   
   
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "Galaxy Auto API"
    description: "API para o gerenciamento de vendas de veículos."
    version: "1.0"
