spring:
    
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: us-east-1
  s3:
    bucketName: ${AWS_BUCKET_NAME}
  cognito:
    userPoolId: ${AWS_COGNITO_USER_POOL_ID}
    jwkSetUri: ${AWS_COGNITO_APP_JWK_SET_URI}
    client:
      id: ${AWS_COGNITO_CLIENT_ID}
      secret: ${AWS_COGNITO_CLIENT_SECRET}
    
